### PR TITLE
fix: populate tables and test ReST table

### PR DESCRIPTION
**Pull request by pohlt**
ReST, markdown, and confluence tables are
tested with the actual installed packages.
Furthermore, the ReST table is being parsed
by docutils for errors.

### CODE REVIEW

**Comment by pohlt** [comment]
This PR is a preparation for issue #73, because currently the ReST tables are tested without actual packages and the resulting ReST string is not being parsed by docutils.

**Comment by raimon49** [comment]
Thank you for P-R. 

I have confirmed running the test including evaluating the rest parser.

We maintain the code style according to [PEP 8](https://www.python.org/dev/peps/pep-0008/).

Could you fix the following?

```bash
============================================================= FAILURES =============================================================
________________________________________________________ pycodestyle-check _________________________________________________________
/git/pip-licenses/test_piplicenses.py:54:80: E501 line too long (95 > 79 characters)
/git/pip-licenses/test_piplicenses.py:59:80: E501 line too long (93 > 79 characters)
```

**Comment by pohlt** [comment]
Sure. Done.

**Comment by raimon49** [comment]
@pohlt OK, thank you for your contribution!!

**Pull request merged**
